### ISSUE TITLE
No need to have DB specific queries

### ISSUE THREAD

**Issue by mudrd8mz** [JotaDF/moodle-blockgame#4]
I don't think you need to use this
```
if ($CFG->dbtype == "mysql" || $CFG->dbtype == "mysqli" || $CFG->dbtype == "mariadb") {
    //
} else if ($CFG->dbtype == "pgsql" || $CFG->dbtype == "postgres") {
    //
}
```
in most if not all places.

You can simply use `COALESCE` as it is SQL standard working on MySQL too. There is no need to use `CURRENT_DATE()` vs `CURRENT_DATE` as the current time can be easily obtained on the PHP level. Etc.

**Comment by JotaDF** [comment]
> I don't think you need to use this
> 
> ```
> if ($CFG->dbtype == "mysql" || $CFG->dbtype == "mysqli" || $CFG->dbtype == "mariadb") {
>     //
> } else if ($CFG->dbtype == "pgsql" || $CFG->dbtype == "postgres") {
>     //
> }
> ```
> 
> in most if not all places.
> 
> You can simply use `COALESCE` as it is SQL standard working on MySQL too. There is no need to use `CURRENT_DATE()` vs `CURRENT_DATE` as the current time can be easily obtained on the PHP level. Etc.


Really, your suggestions helped me to improve my code.

Sorted out.
