### ISSUE TITLE
PHP notices

### ISSUE THREAD

**Issue by mudrd8mz** [JotaDF/moodle-blockgame#6]
Moodle has zero-tolerance policy for PHP notices and warnings. Make sure you have developer debugging enabled when developing Moodle plugins.

![image](https://user-images.githubusercontent.com/85831/100779253-68f1ec80-3408-11eb-9fbd-62ea719d7fc7.png)

**Comment by mudrd8mz** [comment]
![Uploading image.png…]()

**Comment by JotaDF** [comment]
All PHP warnings and warnings have been corrected. 
Thanks for the help.
